# This workflow will run pytest https://docs.pytest.org/en/stable/

name: test app

on:
  push:
    branches: [ "main", "dev", "test/*", "test-*" ]
  pull_request:
    branches: [ "main", "dev", "test/*", "test-*" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install poetry
      run: |
        python -m pip install poetry
    - name: Install dependencies with poetry
      run: |
        python -m poetry install
    - name: Test with pytest
      run: |
        python -m poetry run python -m pytest
